# SPDX-FileCopyrightText: 2024 Joinside <suitor-fall-life@duck.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    reviewers:
      - "Joinsider"
